---
# handlers file for freeradius

- name: restart freeradius
  become: yes
  service:
    name: "{{ freeradius_service_name }}"
    state: restarted
  tags:
    - freeradius

- name: reload freeradius
  become: yes
  service:
    name: "{{ freeradius_service_name }}"
    state: reloaded
  tags:
    - freeradius
